# Generated by Django 4.0.3 on 2022-04-03 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15, verbose_name='День недели')),
                ('date_short', models.CharField(default='None', max_length=15)),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lsn_name', models.CharField(max_length=50, verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['lsn_name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Класс')),
                ('grade_short', models.CharField(default='None', max_length=15)),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_name', models.CharField(max_length=20)),
                ('sign_ru', models.CharField(max_length=20)),
                ('sign_text', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Гороскоп',
                'verbose_name_plural': 'Гороскопы',
            },
        ),
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math', models.CharField(max_length=50, verbose_name='Математика')),
                ('math_short', models.CharField(default='None', max_length=15)),
            ],
            options={
                'verbose_name': 'Математика',
                'verbose_name_plural': 'Математика',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=50, verbose_name='Профиль')),
                ('profile_db', models.CharField(max_length=30, verbose_name='Имя для бота')),
                ('profile_short', models.CharField(default='None', max_length=15)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.grade')),
                ('math', models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to='main_app.math')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['grade', 'profile'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('short_name', models.CharField(max_length=15, unique=True, verbose_name='Короткое имя')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=120, null=True, verbose_name='Название подписки')),
                ('status', models.BooleanField(default=False, null=True, verbose_name='Статус подписки')),
                ('args', models.CharField(max_length=120, null=True, verbose_name='Дополнительно')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Название(ру)')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специальность')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.school')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lsn_number', models.IntegerField(
                    choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'),
                             (9, '9')])),
                ('lsn_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.classroom')),
                ('lsn_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.date')),
                ('lsn_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.grade')),
                ('lsn_math', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.math')),
                ('lsn_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
                ('lsn_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.teacher')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('uses', models.IntegerField(default=1, verbose_name='Использований')),
                ('full_name', models.CharField(max_length=60, null=True, verbose_name='Имя')),
                ('registered', models.BooleanField(default=False, null=True, verbose_name='Зарегистрирован')),
                ('vip', models.BooleanField(default=False, null=True)),
                ('admin', models.BooleanField(default=False, null=True)),
                ('last_seen', models.DateTimeField(null=True)),
                ('school',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.school')),
                ('user_class',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.grade')),
                ('user_math',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.math')),
                ('user_prof',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.profile')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('url', models.URLField(null=True, verbose_name='Ссылка')),
                ('type', models.CharField(blank=True, max_length=60, null=True, verbose_name='Тип')),
                ('tag', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тег')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.school')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.school'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.school'),
        ),
    ]
