# Generated by Django 4.0 on 2022-01-04 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_grade_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='main.grade'),
        ),
    ]
