# Generated by Django 4.0 on 2022-01-05 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_profile_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.grade'),
        ),
    ]
